function buat_login() {
  var judul = document.getElementById("X");
  judul.parentElement.removeChild(judul);
  var a = document.createElement("P");
  a.className = "tulisan_login";
  a.innerHTML = "silahkan mendaftar";
  var el = document.getElementsByTagName("div")[0];
  el.appendChild(a);
  var form = document.createElement("FORM");
  el.appendChild(form);
  var label = document.createElement("label");
  label.className = "label";
  label.innerHTML = "Nama User";
  form.appendChild(label);
  var x = document.createElement("input");
  x.type = "text";
  x.placeholder = "Nama User..";
  x.className = "form_login";
  form.appendChild(x);
  var label1 = document.createElement("label");
  label1.className = "label";
  label1.innerHTML = "Nomor Handphone";
  form.appendChild(label1);
  var y = document.createElement("input");
  y.type = "text";
  y.placeholder = "Nomor Handphone.";
  y.className = "form_login";
  form.appendChild(y);
  var label2 = document.createElement("label");
  label2.className = "label";
  label2.innerHTML = "Username";
  form.appendChild(label2);
  var z = document.createElement("input");
  z.type = "text";
  z.placeholder = "Username atau email ..";
  z.className = "form_login";
  form.appendChild(z);
  var label3 = document.createElement("label");
  label3.className = "label";
  label3.innerHTML = "Password";
  form.appendChild(label3);
  var b = document.createElement("input");
  b.type = "Password";
  b.placeholder = "Password..";
  b.className = "form_login";
  form.appendChild(b);

  var tombol = document.createElement("input");
  tombol.type = "submit";
  tombol.value = "DAFTAR SEKARANG";
  tombol.className = "tombol_login";
  form.appendChild(tombol);
}
